# Copyright (c) 2024, Evgeniy Baskov. All rights reserved

complete -c nsst -l "allow-alternate" -x -a "true false default" -d "Enable alternate screen"
complete -c nsst -l "allow-blinking" -x -a "true false default" -d "Allow blinking text and cursor"
complete -c nsst -l "allow-modify-edit-keypad" -x -a "true false default" -d "Allow modifying edit keypad keys"
complete -c nsst -l "allow-modify-function" -x -a "true false default" -d "Allow modifying function keys"
complete -c nsst -l "allow-modify-keypad" -x -a "true false default" -d "Allow modifying keypad keys"
complete -c nsst -l "allow-modify-misc" -x -a "true false default" -d "Allow modifying miscellaneous keys"
complete -c nsst -l "alpha" -r -d "Background opacity, requires compositor to be running"
complete -c nsst -l "alternate-scroll" -x -a "true false default" -d "Scrolling sends arrow keys escapes in alternate screen"
complete -c nsst -l "answerback-string" -r -d "ENQ report"
complete -c nsst -l "appcursor" -x -a "true false default" -d "Initial application cursor mode value"
complete -c nsst -l "appkey" -x -a "true false default" -d "Initial application keypad mode value"
complete -c nsst -l "autorepeat" -x -a "true false default" -d "Enable key autorepeat"
complete -c nsst -l "autowrap" -x -a "true false default" -d "Initial autowrap setting"
complete -c nsst -l "backend" -x -a "auto x11 wayland x11xrender x11shm waylandshm default" -d "Select rendering backend"
complete -c nsst -l "background" -r -d "Default background color"
complete -c nsst -l "backspace-is-del" -x -a "true false default" -d "Backspace sends DEL instead of BS"
complete -c nsst -l "bell-high-volume" -r -d "High volume value for DECSWBV"
complete -c nsst -l "bell-low-volume" -r -d "Low volume value for DECSWBV"
complete -c nsst -l "bell" -x -a "off low high default" -d "Bell setting"
complete -c nsst -l "blend-all-background" -x -a "true false default" -d "Apply opacity to all background colors, not just default one"
complete -c nsst -l "blend-foreground" -x -a "true false default" -d "Apply opacity to foreground colors"
complete -c nsst -l "blink-color" -r -d "Special color of blinking text"
complete -c nsst -l "blink-time" -r -d "Text blink interval in microseconds"
complete -c nsst -l "bold-color" -r -d "Special color of bold text"
complete -c nsst -l "border" -r -d "Border size"
complete -c nsst -l "bottom-border" -r -d "Bottom border size"
complete -c nsst -l "char-geometry" -x -s G -d "Window geometry in characters"
complete -c nsst -l "config" -r -s C -d "Configuration file path"
complete -c nsst -l "clone-config" -r -s C -d "Copy config from previous window instead of loading it from file"
complete -c nsst -l "cursor-background" -r -d "Default cursor background color"
complete -c nsst -l "cursor-foreground" -r -d "Default cursor foreground color"
complete -c nsst -l "cursor-shape" -x -a "blinking-block block blinking-underline underline blinking-bar bar default" -d "Shape of cursor"
complete -c nsst -l "cursor-width" -r -d "Width of lines that forms cursor"
complete -c nsst -l "cursor-hide-on-input" -r -d "Hide cursor during keyboard input"
complete -c nsst -l "cwd" -r -d "Current working directory for an application"
complete -c nsst -l "daemon" -s d -d "Start terminal as daemon"
complete -c nsst -l "delete-is-del" -x -a "true false default" -d "Delete sends DEL symbol instead of escape sequence"
complete -c nsst -l "double-click-time" -r -d "Time gap in microseconds in witch two mouse presses will be considered double"
complete -c nsst -l "dpi" -r -d "DPI value for fonts"
complete -c nsst -l "erase-scrollback" -x -a "true false default" -d "Allow ED 3 to clear scrollback buffer"
complete -c nsst -l "extended-cir" -x -a "true false default" -d "Report all SGR attributes in DECCIR"
complete -c nsst -l "fixed" -x -a "true false default" -d "Don't allow to change window size, if supported"
complete -c nsst -l "fkey-increment" -r -d "Step in numbering function keys"
complete -c nsst -l "font-gamma" -r -d "Factor of font sharpening"
complete -c nsst -l "font-size" -r -d "Font size in points"
complete -c nsst -l "font-size-step" -r -d "Font size step in points"
complete -c nsst -l "font-spacing" -r -d "Additional spacing for individual symbols"
complete -c nsst -l "font-cache-size" -r -d "Number of cached glyphs per font"
complete -c nsst -l "font" -x -s f -a "(fc-list :spacing=mono family | sed 's/,/\n/g' | sort -u)" -d "Comma-separated list of fontconfig font patterns"
complete -c nsst -l "force-mouse-mod" -r -d "Modifier to force mouse action"
complete -c nsst -l "force-nrcs" -x -a "true false default" -d "Enable NRCS translation when UTF-8 mode is enabled"
complete -c nsst -l "force-scalable" -x -a "true false default" -d "Do not search for pixmap fonts"
complete -c nsst -l "force-wayland-csd" -x -a "true false default" -d "Don't request SSD"
complete -c nsst -l "foreground" -r -d "Default foreground color"
complete -c nsst -l "fork" -x -a "true false default" -d "Fork in daemon mode"
complete -c nsst -l "fps" -r -d "Window refresh rate"
complete -c nsst -l "frame-wait-delay" -r -d "Maximal time since last application output before redraw"
complete -c nsst -l "geometry" -x -s g -d "Window geometry in pixels"
complete -c nsst -l "has-meta" -x -a "true false default" -d "Handle meta/alt"
complete -c nsst -l "help" -s h -d "Print this message and exit"
complete -c nsst -l "horizontal-border" -r -d "Horizontal border size (deprecated)"
complete -c nsst -l "italic-color" -r -d "Special color of italic text"
complete -c nsst -l "keep-clipboard" -x -a "true false default" -d "Reuse copied clipboard content instead of current selection data"
complete -c nsst -l "keep-selection" -x -a "true false default" -d "Don't clear X11 selection when not highlighted"
complete -c nsst -l "keyboard-dialect" -r -d "National replacement character set to be used in non-UTF-8 mode"
complete -c nsst -l "keyboard-mapping" -x -a "legacy vt220 hp sun sco default" -d "Initial keyboard mapping"
complete -c nsst -l "key-break" -r -d "Send break hotkey"
complete -c nsst -l "key-copy" -r -d "Copy to clipboard hotkey"
complete -c nsst -l "key-copy-uri" -r -d "Copy selected URI to clipboard hotkey"
complete -c nsst -l "key-dec-font" -r -d "Decrement font size hotkey"
complete -c nsst -l "key-inc-font" -r -d "Increment font size hotkey"
complete -c nsst -l "key-jump-next-cmd" -r -d "Jump to next command beginning hotkey"
complete -c nsst -l "key-jump-prev-cmd" -r -d "Jump to previous command beginning hotkey"
complete -c nsst -l "key-new-window" -r -d "Create new window hotkey"
complete -c nsst -l "key-numlock" -r -d "'appkey' mode allow toggle hotkey"
complete -c nsst -l "key-paste" -r -d "Paste from clipboard hotkey"
complete -c nsst -l "key-reload-config" -r -d "Reload configuration hotkey"
complete -c nsst -l "key-reset-font" -r -d "Reset font size hotkey"
complete -c nsst -l "key-reset" -r -d "Terminal reset hotkey"
complete -c nsst -l "key-reverse-video" -r -d "Toggle reverse video mode hotkey"
complete -c nsst -l "key-scroll-down" -r -d "Scroll down hotkey"
complete -c nsst -l "key-scroll-up" -r -d "Scroll up hotkey"
complete -c nsst -l "left-border" -r -d "Left border size"
complete -c nsst -l "line-spacing" -r -d "Additional lines vertical spacing"
complete -c nsst -l "lock-keyboard" -x -a "true false default" -d "Disable keyboard input"
complete -c nsst -l "log-level" -x -s L -a "quiet fatal warn info default" -d "Filtering level of logged information"
complete -c nsst -l "luit-path" -r -d "Path to luit executable"
complete -c nsst -l "luit" -x -a "true false default" -d "Run luit if terminal doesn't support encoding by itself"
complete -c nsst -l "margin-bell-column" -r -d "Column at which margin bell rings when armed"
complete -c nsst -l "margin-bell-high-volume" -r -d "High volume value for DECSMBV"
complete -c nsst -l "margin-bell-low-volume" -r -d "Low volume value for DECSMBV"
complete -c nsst -l "margin-bell" -x -a "off low high default" -d "Margin bell setting"
complete -c nsst -l "max-frame-time" -r -d "Maximal time between frames in microseconds"
complete -c nsst -l "meta-sends-escape" -x -a "true false default" -d "Alt/Meta sends escape prefix instead of setting 8-th bit"
complete -c nsst -l "modify-cursor" -x -a "0 1 2 3" -d "Enable encoding modifiers for cursor keys"
complete -c nsst -l "modify-function" -x -a "0 1 2 3" -d "Enable encoding modifiers for function keys"
complete -c nsst -l "modify-keypad" -x -a "0 1 2 3" -d "Enable encoding modifiers keypad keys"
complete -c nsst -l "modify-other-fmt" -x -a "xterm csi-u default" -d "Format of encoding modifiers"
complete -c nsst -l "modify-other" -x -a "0 1 2 3 4" -d "Enable encoding modifiers for other keys"
complete -c nsst -l "nrcs" -x -a "true false default" -d "Enable NRCSs support"
complete -c nsst -l "numlock" -x -a "true false default" -d "Initial numlock state"
complete -c nsst -l "open-cmd" -r -d "A command used to open URIs when clicked"
complete -c nsst -l "override-boxdrawing" -x -a "true false default" -d "Use built-in box drawing characters"
complete -c nsst -l "pixel-mode" -x -a "mono bgr rgb bgrv rgbv default" -d "Sub-pixel rendering mode"
complete -c nsst -l "pointer-shape" -r -a "(ls /usr/share/icons/*/cursors | grep -v cursors: | sort -u)" -d "Default mouse pointer shape for the window"
complete -c nsst -l "print-attributes" -x -a "true false default" -d "Print cell attributes when printing is enabled"
complete -c nsst -l "print-command" -r -d "Program to pipe CSI MC output into"
complete -c nsst -l "printer-file" -r -s o -d "File where CSI MC output to"
complete -c nsst -l "raise-on-bell" -x -a "true false default" -d "Raise terminal window on bell"
complete -c nsst -l "resize-pointer-shape" -r -a "(ls /usr/share/icons/*/cursors | grep -v cursors: | sort -u)" -d "Mouse pointer shape for window resizing"
complete -c nsst -l "reversed-color" -r -d "Special color of reversed text"
complete -c nsst -l "reverse-video" -x -a "true false default" -d "Initial reverse video setting"
complete -c nsst -l "right-border" -r -d "Right border size"
complete -c nsst -l "scroll-amount" -r -d "Number of lines scrolled in a time"
complete -c nsst -l "scrollback-size" -x -s H -d "Number of saved lines"
complete -c nsst -l "scroll-on-input" -x -a "true false default" -d "Scroll view to bottom on key press"
complete -c nsst -l "scroll-on-output" -x -a "true false default" -d "Scroll view to bottom when character in printed"
complete -c nsst -l "selected-background" -r -d "Color of selected background"
complete -c nsst -l "selected-foreground" -r -d "Color of selected text"
complete -c nsst -l "select-scroll-time" -r -d "Delay between scrolls of window while selecting with mouse in microseconds"
complete -c nsst -l "select-to-clipboard" -x -a "true false default" -d "Use CLIPBOARD selection to store highlighted data"
complete -c nsst -l "shell" -r -d "Shell to start in new instance"
complete -c nsst -l "smooth-resize" -x -a "true false default" -d "Don't force window size to be aligned on character size"
complete -c nsst -l "smooth-scroll-delay" -r -d "Delay between scrolls when DECSCLM is enabled"
complete -c nsst -l "smooth-scroll-step" -r -d "Amount of lines per scroll when DECSCLM is enabled"
complete -c nsst -l "smooth-scroll" -x -a "true false default" -d "Initial value of DECSCLM mode"
complete -c nsst -l "socket" -r -s s -d "Daemon socket path"
complete -c nsst -l "special-blink" -x -a "true false default" -d "If special color should be used for blinking text"
complete -c nsst -l "special-bold" -x -a "true false default" -d "If special color should be used for bold text"
complete -c nsst -l "special-italic" -x -a "true false default" -d "If special color should be used for italic text"
complete -c nsst -l "special-reverse" -x -a "true false default" -d "If special color should be used for reverse text"
complete -c nsst -l "special-underlined" -x -a "true false default" -d "If special color should be used for underlined text"
complete -c nsst -l "substitute-fonts" -x -a "true false default" -d "Enable substitute font support"
complete -c nsst -l "sync-timeout" -r -d "Synchronous update timeout"
complete -c nsst -l "tab-width" -r -d "Initial width of tab character"
complete -c nsst -l "term-mod" -r -d "Meaning of 'T' modifier"
complete -c nsst -l "term-name" -x -s D -a "(toe | sed -e 's/\([^\t]*\)\t.*/\1/' -e 's/ //'g  -e '/+/d'| sort -u)" -d "TERM value"
complete -c nsst -l "title" -x -s T -d "Initial window title"
complete -c nsst -l "top-border" -r -d "Top border size"
complete -c nsst -l "trace-characters" -x -a "true false default" -d "Trace interpreted characters"
complete -c nsst -l "trace-controls" -x -a "true false default" -d "Trace interpreted control characters and sequences"
complete -c nsst -l "trace-events" -x -a "true false default" -d "Trace received events"
complete -c nsst -l "trace-fonts" -x -a "true false default" -d "Log font related information"
complete -c nsst -l "trace-input" -x -a "true false default" -d "Trace user input"
complete -c nsst -l "trace-misc" -x -a "true false default" -d "Trace miscellaneous information"
complete -c nsst -l "triple-click-time" -r -d "Time gap in microseconds in witch tree mouse presses will be considered triple"
complete -c nsst -l "underlined-color" -r -d "Special color of underlined text"
complete -c nsst -l "underline-width" -r -d "Text underline width"
complete -c nsst -l "unique-uris" -x -a "true false default" -d "Make distinction between URIs with the same location"
complete -c nsst -l "urgent-on-bell" -x -a "true false default" -d "Set window urgency on bell"
complete -c nsst -l "uri-click-mod" -r -d "keyboard modifier used to click-open URIs"
complete -c nsst -l "uri-color" -r -d "Special color of URI text"
complete -c nsst -l "uri-mode" -x -a "off manual auto default" -d "Allow URI parsing/clicking"
complete -c nsst -l "uri-pointer-shape" -r -a "(ls /usr/share/icons/*/cursors | grep -v cursors: | sort -u)" -d "Mouse pointer shape for hovering over URI"
complete -c nsst -l "uri-underline-color" -r -d "Special color of URI underline"
complete -c nsst -l "use-utf8" -x -a "true false default" -d "Enable UTF-8 I/O"
complete -c nsst -l "version" -s v -d "Print version and exit"
complete -c nsst -l "vertical-border" -r -d "Vertical border size (deprecated)"
complete -c nsst -l "visual-bell-time" -r -d "Length of visual bell"
complete -c nsst -l "visual-bell" -x -a "true false default" -d "Whether bell should be visual or normal"
complete -c nsst -l "vt-version" -x -s t -d "Emulated VT version"
complete -c nsst -l "wait-for-configure-delay" -r -d "Time gap in microseconds waiting for configure after resize request"
complete -c nsst -l "window-class" -x -s V -d "X11 Window class"
complete -c nsst -l "window-ops" -x -a "true false default" -d "Allow window manipulation with escape sequences"
complete -c nsst -l "word-break" -r -d "Symbols treated as word separators when snapping mouse selection"

complete -c nsstc -w nsst
complete -c nsstc -l "quit" -d "Quit the daemon"
